version: "3.8"

services:
  sql_server_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql_server_2022_container
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Pa55w0rd2023
      - MSSQL_PID=Developer

  sqlite_db:
    image: alpine
    container_name: sqlite_container
    command: sh -c "apk add --no-cache sqlite && sqlite3 /database/superheros.db && tail -f /dev/null"
    volumes:
      - ./database:/database

  mysql_db:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superheros
      MYSQL_USER: test
      MYSQL_PASSWORD: Pa55w0rd2023
    ports:
      - 3306:3306
    volumes:
      - mysql_db_data_container:/var/lib/mysql:rw
      - ${PWD}/docker/mysql/initdb_sql_scripts:/docker-entrypoint-initdb.d/:ro
      - ${PWD}/docker/mysql/mysql.conf:/etc/mysql/conf.d
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10

  maria_db:
    image: mariadb:latest
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: superheros
      MYSQL_USER: test
      MYSQL_PASSWORD: Pa55w0rd2023
    ports:
      - 3307:3306
    volumes:
      - mariadb_data_container:/var/lib/mysql:rw
      - ${PWD}/docker/mariadb/initdb_sql_scripts:/docker-entrypoint-initdb.d/:ro
      - ${PWD}/docker/mariadb/mariadb.conf:/etc/mysql/conf.d

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      - POSTGRES_DB=superheros
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=Pa55w0rd2023
    ports:
      - "5432:5432"
    volumes:
      - postgres_db_data_container:/var/lib/postgresql/data:rw
      - ${PWD}/docker/postgres/initdb_sql_scripts:/docker-entrypoint-initdb.d:ro
      - ${PWD}/docker/postgres/postgres.conf:/etc/postgresql/postgresql.conf

volumes:
  mysql_db_data_container:
  mariadb_data_container:
  postgres_db_data_container:
